### ISSUE TITLE
HF->nemo checkpoint conversion script for llama2 models

### ISSUE THREAD

**Issue by ZHAOTING** [aws-neuron/neuronx-nemo-megatron#10]
Hi, while the code for training llama2 architecture (without GQA?) models has been released, I couldn't find any scripts for converting a pre-trained llama2's HF weights to a nemo checkpoint. If that is correct, we can only train a llama2 from scratch instead of finetuning a pre-trained one at the moment.
Is there a plan to release a llama2 conversion script?

**Comment by ZHAOTING** [comment]
It has been solved by the AWS local team in Tokyo.

**Comment by ashivadi** [comment]
Can you share the solution here?

**Comment by ZHAOTING** [comment]
Hi @ashivadi, I am sorry but I am not authorized to disclose the code.
